[tool.ruff]

[tool.ruff.lint]
# Ignore specific rules globally:
ignore = ["D100", "D202", "E402"]
# D100 Missing docstring in public module
# D202 [*] No blank lines allowed after function docstring
# E203 - Whitespace before ':'
# E402 Module level import not at top of file
# E501 - Line too long
# F401 - Unused import
# F841 - Unused variable
# W291 - Trailing whitespace

# ignore rules for specific files/directories:
[tool.ruff.lint.per-file-ignores] 
"tests/*" = ["F401", "F811"]
"__init__.py" = ["F401"]
